services:
  - type: web
    name: iabdCloudRenderYaml
    runtime: node
    repo: https://github.com/ncls-p/render-yaml
    region: frankfurt
    envVars:
      - key: DB_URL
        fromDatabase:
          name: iabdCloudRenderYamlDatabase
          property: connectionString
    plan: free
    buildCommand: npm install
    startCommand: npm start
    preDeployCommand: npm install
databases:
  - name: iabdCloudRenderYamlDatabase
    databaseName: iabdcloud
    user: postgress
    plan: free
