services:
  - type: web
    name: iabdCloudRenderYaml
    runtime: node
    repo: https://github.com/ncls-p/render-yaml
    region: frankfurt
    rootDir: .
    healthCheckPath: /
    envVars:
      - key: DB_URL
        fromDatabase:
          name: iabdCloudRenderYamlDatabase
          property: connectionString
    plan: free
    buildCommand: npm install
    startCommand: npm start
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 15

    preDeployCommand: npm install
    domains:
      - iabdcloud.render.com
    autoDeploy: true

databases:
  - name: iabdCloudRenderYamlDatabase
    databaseName: iabdcloud
    user: postgress

  - name: privateDatabase
    databaseName: private
    ipAllowList: []
    plan: free
