services:
  - type: web
    name: iabdCloudRenderYaml
    runtime: node
    repo: https://github.com/ncls-p/render-yaml
    region: frankfurt
    rootDir: .
    healthCheckPath: /
    envVars:
      - POSGRES_URL=postgres://{{privateDatabase.user}}:{{privateDatabase.password}}@{{privateDatabase.host}}
    plan: free
    buildCommand: npm install
    startCommand: npm start
    scaling:
      min: 1
      max: 1
    preDeployCommand: npm install
    domains:
      - iabdcloud.render.com
    autoDeploy: true

databases:
  - name: iabdCloudRenderYamlDatabase
    databaseName: iabdcloud
    user: postgress

  - name: privateDatabase
    databaseName: private
    ipAllowList: [] # only allow internal connections
