services:
  - type: web
    name: iabdCloudRenderYaml
    runtime: node
    repo: https://github.com/ncls-p/render-yaml
    region: frankfurt
    rootDir: .
    healthCheckPath: /
    envVars:
      - key: STRIPE_API_KEY
        value: Z2V0IG91dHRhIGhlcmUhCg
      - key: DB_URL
        fromDatabase:
          name: iabdCloudRenderYamlDatabase
          property: connectionString

    plan: free
    buildCommand: npm install
    startCommand: npm start
    scaling:
      minInstances: 1
      maxInstances: 1
    preDeployCommand: npm install
    domains:
      - iabdcloud.render.com
    autoDeploy: true

databases:
  - name: iabdCloudRenderYamlDatabase
    databaseName: iabdcloud
    user: postgress

  - name: privateDatabase
    databaseName: private
    ipAllowList: [] # only allow internal connections
